### ISSUE TITLE
google colab installation

### ISSUE THREAD

**Issue by cappelchi** [jordanlab/tagore#5]
I installed tagore  & librsvg2 on google colab and got:
Could not open /usr/lib/tagore-data/base.svg.p.  Please reinstall tagore
Traceback (most recent call last):
  File "/usr/local/bin/tagore", line 242, in <module>
    raise base_e
  File "/usr/local/bin/tagore", line 239, in <module>
    BASE = open(BASE_PATH, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/tagore-data/base.svg.p'.
Folder /usr/lib/tagore-data/ does not exist.
Reinstallation doesn't help.

**Comment by ar0ch** [comment]
@cappelchi better late than never, just released 1.1.2 which should solve this
